server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5

spring:
  application:
    name: qihui-user
  datasource:
    url: jdbc:mysql://39.104.87.202:3306/leyou?useunicode=true&characterEncoding=utf-8
    username: app
    password: 3ubVZhav7CyiLIFN